### ISSUE TITLE
unknown command "drush" for "ddev"

### ISSUE THREAD

**Issue by elgandoz** [vinugawade/ur-cache-cleaner#1]
When hitting the "Clear Cache" in a working copy of Drupal 10 running within DDEV, the extension returns the following errors:

- `Drush error: Error: unknown command "drush" for "ddev" Run 'ddev --help' for usage.`
- `Exception: Error: Command failed: ddev drush cr Error: unknown command "drush" for "ddev" Run 'ddev --help' for usage.`

Running `ddev drush cr` in the terminal (integrated or the system one) works as expected. Not that matter in this instance but I also have Drush launcher installed.

- MacOS Ventura 13.4.1
- Visual Studio Code 1.80.1
- ddev 1.21.6
- UR Cache Cleaner 1.2.0

<img width="1233" alt="Screenshot 2023-07-18 at 10 57 12" src="https://github.com/vinugawade/ur-cache-cleaner/assets/5859926/a610a359-f778-4009-b07f-a5d4d623d030">

**Comment by vinugawade** [comment]
Hey @elgandoz, thanks for bringing this issue to my attention. I'll investigate it as soon as possible.

**Comment by vinay-osseed** [comment]
@elgandoz Could you please provide me with the information regarding the version of `Drush`? Thank you!

**Comment by elgandoz** [comment]
**Drush Launcher Version**: `0.10.2` (not really used)
**Ddev container drush** (installed via composer as project dependency): at the time I wrote this issue it was `11.6.0` but I now switched to `12.1.2.0` given I'm working on a Drupal 10.1 project.

Regardless of the version, it seems the extension cannot find the `drush` command.

This is another error I get now when I open VSCode within the project folder (root of drupal/recommended-project, ddev running): `Drush Error: Command failed: drush status --root=[project-path]`

<img width="442" alt="Screenshot 2023-07-25 at 10 17 24" src="https://github.com/vinugawade/ur-cache-cleaner/assets/5859926/16ffcb57-7a8d-4899-9528-68dcae3e0b37">

**Comment by vinay-osseed** [comment]
@elgandoz, You are correct that it's unable to find `drush`. Let me check this issue, and thank you for providing additional information.

**Comment by vinay-osseed** [comment]
Hi @elgandoz,

I just wanted to let you know that I have sent you a beta version of the extension via email for testing purposes. Please check your inbox for the email containing the necessary files. 

I genuinely appreciate your willingness to assist me with the testing process. Your feedback and insights will play a crucial role in improving the extension and ensuring its quality before the final release. If you have any questions or face any issues while testing, please feel free to reach out to me.

Thank you once again for your support and active involvement in this project. I eagerly await your feedback on the beta version.
